/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Home/houseProject.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-2.49, 0, 1.54]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.2}>
          <primitive object={nodes.Pusat} />
          <skinnedMesh name="Beruang_Badan" geometry={nodes.Beruang_Badan.geometry} material={materials["Material.001"]} skeleton={nodes.Beruang_Badan.skeleton} />
        </group>
        <group name="Plane022" position={[-0.4, 0.62, 2.16]} scale={[0.71, 0.71, 0.81]} />
        <group name="Vert001" position={[1.36, 2.98, -2.15]} />
        <group name="Plane046" position={[1.31, 2.5, 3.13]} rotation={[-0.01, 0.03, 0.49]} />
        <group name="Mball010" position={[-2.33, 0.14, 3.48]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.09} />
        <group name="Mball011" position={[-2.14, 0.13, 3.41]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.1} />
        <group name="Mball012" position={[-2, 0.11, 3.57]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.08} />
        <group name="Mball013" position={[-2.05, 0.26, 3.51]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.08} />
        <group name="Mball014" position={[-2.2, 0.24, 3.58]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.08} />
        <group name="Mball015" position={[-2.26, 0.25, 3.46]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.08} />
        <group name="Mball016" position={[-2.1, 0.12, 3.66]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.05} />
        <group name="Mball017" position={[-2.3, 0.09, 3.6]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.05} />
        <group name="Mball018" position={[-2.18, 0.14, 3.61]} scale={0.08} />
        <group name="Mball019" position={[-0.23, 0.09, -2.84]} scale={0.14} />
        <group name="Mball020" position={[-0.18, 0.29, -2.82]} scale={[0.1, 0.1, 0.09]} />
        <group name="Mball021" position={[-0.18, 0.44, -2.82]} scale={[0.08, 0.06, 0.06]} />
        <group name="Mball022" position={[-0.18, 0.22, -2.75]} scale={0.06} />
        <group name="Mball023" position={[-0.15, 0.51, -2.81]} scale={[0.05, 0.04, 0.04]} />
        <group name="Mball024" position={[-0.24, 0.23, -2.88]} scale={0.06} />
        <group name="Mball025" position={[-0.21, 0.37, -2.82]} scale={0.06} />
        <group name="Mball001" position={[-0.1, 0.17, 0.69]} rotation={[0, -1.05, 0]} scale={0.08} />
        <group name="Mball009" position={[-0.17, 0.08, 0.65]} rotation={[0, -0.53, 0]} scale={0.06}>
          <group name="Mball002" position={[0.56, 0.99, 2.33]} scale={1.71} />
          <group name="Mball003" position={[-3.26, 0.73, 3.75]} scale={1.95} />
          <group name="Mball004" position={[-5.81, 0.27, 0.55]} scale={1.66} />
          <group name="Mball005" position={[-4.97, 3.25, 1.64]} scale={1.66} />
          <group name="Mball006" position={[-1.94, 2.95, 0.42]} scale={1.66} />
          <group name="Mball007" position={[-0.88, 3.04, 2.69]} scale={1.66} />
          <group name="Mball008" position={[-3.93, 0.44, -1.26]} />
          <group name="Mball026" position={[-2.42, 0.83, -0.21]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={1.6} />
        </group>
        <group name="Empty" position={[1.51, 3.01, -1.01]} />
        <group name="Plane001" position={[1.51, 0, -1.03]} scale={[1, 1, 1.99]}>
          <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials[" house walls"]} />
          <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials.Windows} />
          <mesh name="Plane005_3" geometry={nodes.Plane005_3.geometry} material={materials.ceiling} />
        </group>
        <group name="Plane002" position={[1.51, 0, 2.17]} scale={[0.71, 0.71, 0.81]}>
          <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials[" house walls"]} />
          <mesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials.Windows} />
          <mesh name="Plane006_3" geometry={nodes.Plane006_3.geometry} material={materials.ceiling} />
        </group>
        <group name="Plane003" position={[-0.4, 0.62, 2.16]} scale={[0.71, 0.71, 0.81]}>
          <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials[" house walls"]} />
          <mesh name="Plane007_2" geometry={nodes.Plane007_2.geometry} material={materials.Windows} />
          <mesh name="Plane007_3" geometry={nodes.Plane007_3.geometry} material={materials.ceiling} />
        </group>
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.ceiling} position={[1.51, -0.04, -1.03]} scale={[1.01, 1.01, 2.15]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.ceiling} position={[1.51, -0.06, 1.77]} scale={[0.72, 0.72, 0.85]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.ceiling} position={[-0.4, 0.61, 2.16]} scale={[0.72, 0.72, 0.81]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials[" house walls"]} position={[1.48, 1.46, -3.17]} scale={[0.64, 1, 1.99]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.Grey} position={[1.51, 0, -1.03]} scale={[1, 1, 2.13]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.Grey} position={[1.51, 0, 1.77]} scale={[0.71, 0.71, 0.84]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.Grey} position={[-0.4, 0.64, 2.16]} scale={[0.7, 0.7, 0.79]} />
        <group name="Plane011" position={[1.37, 0, -1.03]} scale={[0.9, 0.88, 1.4]}>
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials.Windows} />
          <mesh name="Plane018_2" geometry={nodes.Plane018_2.geometry} material={materials.ceiling} />
        </group>
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.ceiling} position={[1.49, 0, -1.03]} scale={[1, 1, 1.99]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials.ceiling} position={[1.46, 0, 1.8]} scale={[0.71, 0.71, 0.81]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials.garage} position={[-0.4, 0.62, 2.16]} scale={[0.71, 0.71, 0.81]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.garage} position={[-1.14, 0.14, 2.16]} scale={[0.04, 0.19, 0.2]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.floor} position={[-0.04, -0.01, -1.05]} scale={[1.36, 0.77, 1.04]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials.ceiling} position={[1.51, 0, 0.59]} scale={[0.71, 0.71, 0.81]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[1.51, 0, -1.03]} scale={[1, 1, 1.99]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.ceiling} position={[-0.42, 0.62, 2.16]} scale={[0.71, 0.71, 0.81]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials.ceiling} position={[-1.22, 1.25, 2.16]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 0.71, 0.81]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials.mailbox} position={[-3.64, 0.67, 0.75]} />
        <mesh name="Plane061" geometry={nodes.Plane061.geometry} material={materials.ceiling} position={[1.36, -0.01, -1.03]} scale={[0.9, 0.88, 1.4]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Bricks} position={[1.1, 0.99, -3.39]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.Bricks} position={[0.09, 0, -0.14]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Bricks} position={[-0.02, 0, -0.7]} />
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Bricks} position={[-0.02, 0, -0.84]} />
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Bricks} position={[0.44, 0, 0.39]} />
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Bricks} position={[0.32, 0, 0.24]} />
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Bricks} position={[0.55, 0.01, -0.72]} />
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Bricks} position={[0.68, 0.01, 0.95]} />
          <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Bricks} position={[0.68, 0.01, -0.72]} />
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Bricks} position={[0.62, 0.01, 1]} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Bricks} position={[0.55, 0, -0.63]} />
          <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Bricks} position={[0.62, 0.01, 1.07]} />
          <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Bricks} position={[0.68, 0.01, 1.01]} />
          <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Bricks} position={[0.52, -0.07, 0.19]} />
          <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Bricks} position={[0.52, -0.07, 0.91]} />
          <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Bricks} position={[0.28, -0.27, -0.45]} />
          <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Bricks} position={[0.22, 0, 1.44]} />
        </mesh>
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials.Slabs} position={[0.25, 2.4, -2.82]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.Slabs} position={[0.43, 2.48, -2.62]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials.Slabs} position={[0.25, 2.4, -2.41]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials.Slabs} position={[1.06, 2.78, -1.19]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials.Slabs} position={[0.88, 2.69, -0.97]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials.Slabs} position={[0.7, 2.6, -1.19]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials.Slabs} position={[0.56, 2.55, 0.14]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials.Slabs} position={[0.56, 2.55, 0.55]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials.Slabs} position={[0.38, 2.46, 0.45]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials.Slabs} position={[0.38, 2.46, 0.83]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials.Slabs} position={[0.56, 2.55, -0.48]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials.Slabs} position={[1.25, 2.88, 0.84]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials.Slabs} position={[1.06, 2.78, -2.62]} rotation={[0, 0, -2.69]} />
        <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials.Slabs} position={[1.22, 2.45, 2.3]} rotation={[0, 0, 0.49]} />
        <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials.Slabs} position={[0.86, 2.26, 1.85]} rotation={[0, 0, 0.49]} />
        <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials.Slabs} position={[0.95, 2.31, 2.68]} rotation={[0, 0, 0.49]} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials.Slabs} position={[0.63, 2.14, 2.14]} rotation={[0, 0, 0.49]} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials.Slabs} position={[1.33, 2.51, 3.21]} rotation={[-0.02, 0.03, 0.49]} />
        <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials.Slabs} position={[0.56, 2.1, 1.18]} rotation={[-0.02, 0.03, 0.49]} />
        <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={materials.Slabs} position={[0.79, 2.23, 1.34]} rotation={[0.01, -0.03, 0.49]} />
        <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials.Slabs} position={[0.61, 2.13, 3.24]} rotation={[-0.01, 0.03, 0.49]} />
        <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials.Slabs} position={[-0.23, 1.18, 1.11]} rotation={[-0.41, -0.07, 0]} />
        <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials.Slabs} position={[-0.43, 1.53, 1.9]} rotation={[-0.41, 1.48, 0]} />
        <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials.Slabs} position={[-0.75, 1.43, 1.68]} rotation={[-0.41, 1.48, 0]} />
        <mesh name="Plane053" geometry={nodes.Plane053.geometry} material={materials.Slabs} position={[-0.13, 1.53, 1.9]} rotation={[-0.41, 1.48, 0]} />
        <mesh name="Plane054" geometry={nodes.Plane054.geometry} material={materials.Slabs} position={[-0.55, 1.45, 2.6]} rotation={[0.41, -1.49, 0]} />
        <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials.Slabs} position={[-0.63, 1.43, 2.64]} rotation={[0.41, 1.48, 0]} />
        <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials.Slabs} position={[-0.47, 1.42, 2.66]} rotation={[0.41, 1.48, 0]} />
        <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials.Slabs} position={[-0.13, 1.53, 1.9]} rotation={[-0.41, 1.48, 0]} />
        <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials.Slabs} position={[-0.02, 1.24, 3.08]} rotation={[0.41, -1.49, 0]} />
        <mesh name="Plane059" geometry={nodes.Plane059.geometry} material={materials.Slabs} position={[-1.1, 1.14, 3.31]} rotation={[0.43, -1.49, 0.01]} />
        <mesh name="Plane060" geometry={nodes.Plane060.geometry} material={materials.Slabs} position={[-0.96, 1.16, 3.27]} rotation={[0.42, -1.49, 0]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.mailbox} position={[-3.51, 0.64, 0.81]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials["Wood mailbox"]} position={[-3.52, 0.24, 0.82]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Antenna} position={[1.36, 2.77, -2.15]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.floor} position={[0, -0.02, 0]} scale={[4, 1, 4]}>
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.door} position={[0.38, 0, -0.26]} scale={[0.25, 1, 0.5]} />
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials.ceiling} position={[0.38, 0, -0.26]} scale={[0.25, 1, 0.5]} />
        </mesh>
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.grass} position={[0, -0.02, 0]} scale={[4, 1, 4]} />
        <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials.grass} position={[-3.41, 0.07, -0.86]} />
        <mesh name="Plane063" geometry={nodes.Plane063.geometry} material={materials.grass} position={[-2.54, 0.07, -3.3]} />
        <mesh name="Plane064" geometry={nodes.Plane064.geometry} material={materials.grass} position={[-1.72, 0.09, -3.03]} />
        <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={materials.grass} position={[-3.69, 0.07, 0.36]} />
        <mesh name="Plane066" geometry={nodes.Plane066.geometry} material={materials.grass} position={[-1.76, 0.07, 0.98]} />
        <mesh name="Plane067" geometry={nodes.Plane067.geometry} material={materials.grass} position={[2.51, 0.07, -3.58]} />
        <mesh name="Plane068" geometry={nodes.Plane068.geometry} material={materials.rug} position={[-0.11, 0.07, -1.03]} scale={[1.2, 1, 1.45]} />
        <mesh name="Plane069" geometry={nodes.Plane069.geometry} material={materials.grass} position={[3.55, 0.07, -0.93]} />
        <mesh name="Plane070" geometry={nodes.Plane070.geometry} material={materials.grass} position={[3.41, 0.07, 1.97]} />
        <mesh name="Plane071" geometry={nodes.Plane071.geometry} material={materials.grass} position={[-2.54, 0.07, 3.41]} />
        <mesh name="Plane072" geometry={nodes.Plane072.geometry} material={materials.grass} position={[3.46, 0.07, 3.25]} />
        <mesh name="Roundcube" geometry={nodes.Roundcube.geometry} material={materials.mailbox} position={[0.13, 0.49, -1.24]} scale={0.02} />
      </group>
    </group>
  );
}

useGLTF.preload("/Home/houseProject.glb");
